#!/bin/zsh
runner="$(echo "$([ -x "$(which npm)" ] && echo "npm")\n$([ -x "$(which yarn)" ] && echo "yarn")\n$([ -x "$(which pnpm)" ] && echo "pnpm")\nnode" | shuf | head -1)"

[ -n "$@" ] && cmd="dev" || cmd="$@"
if [ "$runner" = "node" ]; then
  node node_modules/vite/bin/vite.js $cmd
else
  "$runner" run $cmd
fi
